//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalServices.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechnicalServices.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to log in to add an order.
        /// </summary>
        internal static string A101 {
            get {
                return ResourceManager.GetString("A101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not agree to the terms of service.
        /// </summary>
        internal static string A102 {
            get {
                return ResourceManager.GetString("A102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order is marked as finished by the technician do you accept that the order is finshed.
        /// </summary>
        internal static string A103 {
            get {
                return ResourceManager.GetString("A103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do you want to review the order this will only take a minute put it is very emportent.
        /// </summary>
        internal static string A104 {
            get {
                return ResourceManager.GetString("A104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your about to send this order to be reviewed by an admin,are you sure you want to do that?.
        /// </summary>
        internal static string A105 {
            get {
                return ResourceManager.GetString("A105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can not see the tech details you have to chose a responce first.
        /// </summary>
        internal static string A106 {
            get {
                return ResourceManager.GetString("A106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sour you want to cancel this order this action may cost you some fee.
        /// </summary>
        internal static string A107 {
            get {
                return ResourceManager.GetString("A107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you already chose a response for this order.
        /// </summary>
        internal static string A108 {
            get {
                return ResourceManager.GetString("A108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your about to choose this response to the order, are you sure?.
        /// </summary>
        internal static string A109 {
            get {
                return ResourceManager.GetString("A109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your about to marke this order as finished the user stel has to agree.
        /// </summary>
        internal static string A110 {
            get {
                return ResourceManager.GetString("A110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account activation.
        /// </summary>
        internal static string accountactivation {
            get {
                return ResourceManager.GetString("accountactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add responce.
        /// </summary>
        internal static string AddResponce {
            get {
                return ResourceManager.GetString("AddResponce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air conditioning installations.
        /// </summary>
        internal static string Airconditioninginstallations {
            get {
                return ResourceManager.GetString("Airconditioninginstallations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air conditioning Maintenance.
        /// </summary>
        internal static string AirconditioningMaintenance {
            get {
                return ResourceManager.GetString("AirconditioningMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluminum.
        /// </summary>
        internal static string Aluminum {
            get {
                return ResourceManager.GetString("Aluminum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammount:.
        /// </summary>
        internal static string Ammount {
            get {
                return ResourceManager.GetString("Ammount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a response has been chosen.
        /// </summary>
        internal static string aresponsehasbeenchosen {
            get {
                return ResourceManager.GetString("aresponsehasbeenchosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ari conditioning extensions.
        /// </summary>
        internal static string Ariconditioningextensions {
            get {
                return ResourceManager.GetString("Ariconditioningextensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canceled by the Technican.
        /// </summary>
        internal static string canceledbytheTechnican {
            get {
                return ResourceManager.GetString("canceledbytheTechnican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel order fee.
        /// </summary>
        internal static string Cancelorderfee {
            get {
                return ResourceManager.GetString("Cancelorderfee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpentry.
        /// </summary>
        internal static string Carpentry {
            get {
                return ResourceManager.GetString("Carpentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceiling.
        /// </summary>
        internal static string Ceiling {
            get {
                return ResourceManager.GetString("Ceiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this response.
        /// </summary>
        internal static string ChooseThiResponse {
            get {
                return ResourceManager.GetString("ChooseThiResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a time:.
        /// </summary>
        internal static string ChooseTime {
            get {
                return ResourceManager.GetString("ChooseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose a date:.
        /// </summary>
        internal static string ChoseDate {
            get {
                return ResourceManager.GetString("ChoseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Water Installation.
        /// </summary>
        internal static string CleanWaterInstallation {
            get {
                return ResourceManager.GetString("CleanWaterInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Water Installation Maintenance.
        /// </summary>
        internal static string CleanWaterInstallationMaintenance {
            get {
                return ResourceManager.GetString("CleanWaterInstallationMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyAccount:.
        /// </summary>
        internal static string CompanyAccount {
            get {
                return ResourceManager.GetString("CompanyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditioning and cooling.
        /// </summary>
        internal static string Conditioningandcooling {
            get {
                return ResourceManager.GetString("Conditioningandcooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooling Maintenance.
        /// </summary>
        internal static string CoolingMaintenance {
            get {
                return ResourceManager.GetString("CoolingMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decor.
        /// </summary>
        internal static string Decor {
            get {
                return ResourceManager.GetString("Decor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration consultation.
        /// </summary>
        internal static string Decorationconsultation {
            get {
                return ResourceManager.GetString("Decorationconsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted by the User.
        /// </summary>
        internal static string DeletedbytheUser {
            get {
                return ResourceManager.GetString("DeletedbytheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Oreder.
        /// </summary>
        internal static string DeleteOreder {
            get {
                return ResourceManager.GetString("DeleteOreder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Left a field empty.
        /// </summary>
        internal static string E101 {
            get {
                return ResourceManager.GetString("E101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your enterd an invaled email.
        /// </summary>
        internal static string E102 {
            get {
                return ResourceManager.GetString("E102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You enterd the wrong Email or password.
        /// </summary>
        internal static string E103 {
            get {
                return ResourceManager.GetString("E103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is pande.
        /// </summary>
        internal static string E104 {
            get {
                return ResourceManager.GetString("E104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There no internet connection.
        /// </summary>
        internal static string E105 {
            get {
                return ResourceManager.GetString("E105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred.
        /// </summary>
        internal static string E106 {
            get {
                return ResourceManager.GetString("E106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The estimatid Time should be less than 8.
        /// </summary>
        internal static string E107 {
            get {
                return ResourceManager.GetString("E107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You enterd the wrong code.
        /// </summary>
        internal static string E108 {
            get {
                return ResourceManager.GetString("E108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered an invaled password.
        /// </summary>
        internal static string E109 {
            get {
                return ResourceManager.GetString("E109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password and Confirm Password is not the same.
        /// </summary>
        internal static string E110 {
            get {
                return ResourceManager.GetString("E110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you have enterd is not registerd.
        /// </summary>
        internal static string E111 {
            get {
                return ResourceManager.GetString("E111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered an invaled email the email should have @gmail.com in it.
        /// </summary>
        internal static string E112 {
            get {
                return ResourceManager.GetString("E112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is already in use.
        /// </summary>
        internal static string E113 {
            get {
                return ResourceManager.GetString("E113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered an invaled username.
        /// </summary>
        internal static string E114 {
            get {
                return ResourceManager.GetString("E114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Social Security Number is already in use.
        /// </summary>
        internal static string E115 {
            get {
                return ResourceManager.GetString("E115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered an invaled Social Security Number.
        /// </summary>
        internal static string E116 {
            get {
                return ResourceManager.GetString("E116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the phone number is alredy in use.
        /// </summary>
        internal static string E117 {
            get {
                return ResourceManager.GetString("E117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the email that you entred is already in use try to chose forgot password.
        /// </summary>
        internal static string E118 {
            get {
                return ResourceManager.GetString("E118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You enterd an invaled Phone Number.
        /// </summary>
        internal static string E119 {
            get {
                return ResourceManager.GetString("E119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add orders this may becose you alredy have a lot of order or your balance is low.
        /// </summary>
        internal static string E120 {
            get {
                return ResourceManager.GetString("E120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical.
        /// </summary>
        internal static string Electrical {
            get {
                return ResourceManager.GetString("Electrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical installations.
        /// </summary>
        internal static string Electricalinstallations {
            get {
                return ResourceManager.GetString("Electricalinstallations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Maintenance.
        /// </summary>
        internal static string ElectricalMaintenance {
            get {
                return ResourceManager.GetString("ElectricalMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimatid Price:.
        /// </summary>
        internal static string EstimatidPrice {
            get {
                return ResourceManager.GetString("EstimatidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esttimatid Time:.
        /// </summary>
        internal static string EsttimatidTime {
            get {
                return ResourceManager.GetString("EsttimatidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expereanc level:.
        /// </summary>
        internal static string ExpereancLevel {
            get {
                return ResourceManager.GetString("ExpereancLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External installations.
        /// </summary>
        internal static string Externalinstallations {
            get {
                return ResourceManager.GetString("Externalinstallations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedBack massege:.
        /// </summary>
        internal static string FeedBackmassege {
            get {
                return ResourceManager.GetString("FeedBackmassege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished By the Technician.
        /// </summary>
        internal static string FinishedBytheTechnician {
            get {
                return ResourceManager.GetString("FinishedBytheTechnician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flooring.
        /// </summary>
        internal static string Flooring {
            get {
                return ResourceManager.GetString("Flooring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name:.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home appliances maintenance.
        /// </summary>
        internal static string Homeappliancesmaintenance {
            get {
                return ResourceManager.GetString("Homeappliancesmaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i have read and agree to the terms of service.
        /// </summary>
        internal static string IHaveRead {
            get {
                return ResourceManager.GetString("IHaveRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal installations.
        /// </summary>
        internal static string Internalinstallations {
            get {
                return ResourceManager.GetString("Internalinstallations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi and welcome to our Technical services app.
        /// </summary>
        internal static string M101 {
            get {
                return ResourceManager.GetString("M101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this app let you order any services you want and someone is going to help you.
        /// </summary>
        internal static string M102 {
            get {
                return ResourceManager.GetString("M102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as finished.
        /// </summary>
        internal static string MarkAsFinished {
            get {
                return ResourceManager.GetString("MarkAsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as read.
        /// </summary>
        internal static string MarkAsRead {
            get {
                return ResourceManager.GetString("MarkAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        internal static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Ratings.
        /// </summary>
        internal static string MyRatings {
            get {
                return ResourceManager.GetString("MyRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Services.
        /// </summary>
        internal static string MyServices {
            get {
                return ResourceManager.GetString("MyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network installations Maintenance.
        /// </summary>
        internal static string NetworkinstallationsMaintenance {
            get {
                return ResourceManager.GetString("NetworkinstallationsMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Orders.
        /// </summary>
        internal static string NewOrders {
            get {
                return ResourceManager.GetString("NewOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order fee.
        /// </summary>
        internal static string orderfee {
            get {
                return ResourceManager.GetString("orderfee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Is in administration review.
        /// </summary>
        internal static string OrderIsinadministrationreview {
            get {
                return ResourceManager.GetString("OrderIsinadministrationreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order location.
        /// </summary>
        internal static string OrderLocation {
            get {
                return ResourceManager.GetString("OrderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order number:.
        /// </summary>
        internal static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Responses.
        /// </summary>
        internal static string OrderResponses {
            get {
                return ResourceManager.GetString("OrderResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status:.
        /// </summary>
        internal static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painting.
        /// </summary>
        internal static string Painting {
            get {
                return ResourceManager.GetString("Painting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Descriptopn:.
        /// </summary>
        internal static string PaymentDescriptopn {
            get {
                return ResourceManager.GetString("PaymentDescriptopn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type:.
        /// </summary>
        internal static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Maintenance.
        /// </summary>
        internal static string Phonemaintenance {
            get {
                return ResourceManager.GetString("Phonemaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number:.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        internal static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Code.
        /// </summary>
        internal static string ResendCode {
            get {
                return ResourceManager.GetString("ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order hase been added successfully.
        /// </summary>
        internal static string S101 {
            get {
                return ResourceManager.GetString("S101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Response has been added Successfully.
        /// </summary>
        internal static string S102 {
            get {
                return ResourceManager.GetString("S102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ratings has beeh Saved.
        /// </summary>
        internal static string S103 {
            get {
                return ResourceManager.GetString("S103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password hase been changed.
        /// </summary>
        internal static string S104 {
            get {
                return ResourceManager.GetString("S104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account have been created successfully.
        /// </summary>
        internal static string S105 {
            get {
                return ResourceManager.GetString("S105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is fineshed.
        /// </summary>
        internal static string S106 {
            get {
                return ResourceManager.GetString("S106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your order is been reviewed by an admin this may take a day or tow.
        /// </summary>
        internal static string S107 {
            get {
                return ResourceManager.GetString("S107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your order has been deleted.
        /// </summary>
        internal static string S108 {
            get {
                return ResourceManager.GetString("S108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the response has been choosen.
        /// </summary>
        internal static string S109 {
            get {
                return ResourceManager.GetString("S109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the order status has been changed.
        /// </summary>
        internal static string S110 {
            get {
                return ResourceManager.GetString("S110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satelite equipment Maintenance.
        /// </summary>
        internal static string SateliteequipmentMaintenance {
            get {
                return ResourceManager.GetString("SateliteequipmentMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Devices installations.
        /// </summary>
        internal static string SecurityDevicesinstallations {
            get {
                return ResourceManager.GetString("SecurityDevicesinstallations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Devices Maintenance.
        /// </summary>
        internal static string SecurityDevicesMaintenance {
            get {
                return ResourceManager.GetString("SecurityDevicesMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service:.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sewer Water Installation.
        /// </summary>
        internal static string SewerWaterInstallation {
            get {
                return ResourceManager.GetString("SewerWaterInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sewer Water Installation Maintenance.
        /// </summary>
        internal static string SewerWaterInstallationMaintenance {
            get {
                return ResourceManager.GetString("SewerWaterInstallationMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Security Number:.
        /// </summary>
        internal static string SSN {
            get {
                return ResourceManager.GetString("SSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully.
        /// </summary>
        internal static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician Account.
        /// </summary>
        internal static string TechnicianAccount {
            get {
                return ResourceManager.GetString("TechnicianAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician Details.
        /// </summary>
        internal static string TechnicianDetails {
            get {
                return ResourceManager.GetString("TechnicianDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician Experience Level:.
        /// </summary>
        internal static string TechnicianExperienceLevel {
            get {
                return ResourceManager.GetString("TechnicianExperienceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician phone number:.
        /// </summary>
        internal static string TechnicianPhoneNumber {
            get {
                return ResourceManager.GetString("TechnicianPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician Ratings:.
        /// </summary>
        internal static string TechnicianRatings {
            get {
                return ResourceManager.GetString("TechnicianRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician UserName:.
        /// </summary>
        internal static string TechnicianUserName {
            get {
                return ResourceManager.GetString("TechnicianUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the order is finished.
        /// </summary>
        internal static string theorderisfinished {
            get {
                return ResourceManager.GetString("theorderisfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Request sent successfully.
        /// </summary>
        internal static string theRequestsentsuccessfully {
            get {
                return ResourceManager.GetString("theRequestsentsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user is satisfied.
        /// </summary>
        internal static string theuserissatisfied {
            get {
                return ResourceManager.GetString("theuserissatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing.
        /// </summary>
        internal static string Timing {
            get {
                return ResourceManager.GetString("Timing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to explain your problem in the best way to get the best responses.
        /// </summary>
        internal static string TryToExplain {
            get {
                return ResourceManager.GetString("TryToExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown problem.
        /// </summary>
        internal static string Unknownproblem {
            get {
                return ResourceManager.GetString("Unknownproblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown problem.
        /// </summary>
        internal static string Unknownproplem {
            get {
                return ResourceManager.GetString("Unknownproplem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Balance:.
        /// </summary>
        internal static string UserBalance {
            get {
                return ResourceManager.GetString("UserBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User incomes.
        /// </summary>
        internal static string UserIncomes {
            get {
                return ResourceManager.GetString("UserIncomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName:.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Payments.
        /// </summary>
        internal static string UserPayments {
            get {
                return ResourceManager.GetString("UserPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User phone number:.
        /// </summary>
        internal static string UserPhoneNumber {
            get {
                return ResourceManager.GetString("UserPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code:.
        /// </summary>
        internal static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor.
        /// </summary>
        internal static string Visitor {
            get {
                return ResourceManager.GetString("Visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Washing machine Maintenance.
        /// </summary>
        internal static string WashingmachineMaintenance {
            get {
                return ResourceManager.GetString("WashingmachineMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Accessories Installation.
        /// </summary>
        internal static string WaterAccessoriesInstallation {
            get {
                return ResourceManager.GetString("WaterAccessoriesInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water installation maintenance.
        /// </summary>
        internal static string Waterinstallationmaintenance {
            get {
                return ResourceManager.GetString("Waterinstallationmaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we have send the Verification code to the email that you have enterd.
        /// </summary>
        internal static string WeHaveSend {
            get {
                return ResourceManager.GetString("WeHaveSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        internal static string Wood {
            get {
                return ResourceManager.GetString("Wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have an account.
        /// </summary>
        internal static string YouDontHaveAnAccount {
            get {
                return ResourceManager.GetString("YouDontHaveAnAccount", resourceCulture);
            }
        }
    }
}
